### ISSUE TITLE
NPE causing all overlays to crash

### ISSUE THREAD

**Issue by ZacBlanco** [Toofifty/easy-giantsfoundry#30]
Was fishing on Karamja on a leagues world and this plugin seemed to have crashed the overlays on Runelite. Here's the stacktrace:

<details><summary>Stacktrace</summary>
<p>

```
2023-12-10 22:49:09 PST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.IllegalArgumentException: null
	at client.eh(client.java:54166)
	at client.createMenuEntry(client.java:11494)
	at com.github.adituv.runedokuplugin.RunedokuPlugin.makeMarkMenuEntry(RunedokuPlugin.java:201)
	at com.github.adituv.runedokuplugin.RunedokuPlugin.onMenuOpened(RunedokuPlugin.java:167)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:194)
	at client.cj(client.java:61335)
	at client.ff(client.java)
	at client.gr(client.java:1164)
	at client.qu(client.java:24150)
	at client.hm(client.java:3516)
	at client.bp(client.java:1161)
	at bm.an(bm.java:394)
	at bm.ov(bm.java)
	at bm.run(bm.java:33867)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-12-11 22:13:06 PST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
vf: 
	at iw.ah(iw.java:61540)
	at rc.bw(rc.java:52)
	at rc.bp(rc.java:45)
	at cj.ae(cj.java:252)
	at ds.ab(ds.java:157)
	at ds.ar(ds.java:147)
	at ds.isFriend(ds.java)
	at net.runelite.client.plugins.screenshot.ScreenshotPlugin.onActorDeath(ScreenshotPlugin.java:306)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:194)
	at df.dn(df.java:56836)
	at df.ku(df.java)
	at cc.ah(cc.java:244)
	at client.jt(client.java:1683)
	at client.hm(client.java:3033)
	at client.bp(client.java:1161)
	at bm.an(bm.java:394)
	at bm.ov(bm.java)
	at bm.run(bm.java:33867)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at vj.wc(vj.java)
	at rc.bw(rc.java:51)
	... 19 common frames omitted
2023-12-11 22:52:11 PST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at com.toofifty.easygiantsfoundry.FoundryOverlay3D.drawKovacIfHandIn(FoundryOverlay3D.java:218)
	at com.toofifty.easygiantsfoundry.FoundryOverlay3D.render(FoundryOverlay3D.java:93)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:502)
	at kg.tr(kg.java:40411)
	at kg.ac(kg.java:122)
	at nb.jp(nb.java:4932)
	at bz.lk(bz.java:10788)
	at bz.lk(bz.java:10819)
	at ag.ln(ag.java:10683)
	at client.ik(client.java:4598)
	at client.bw(client.java:1191)
	at bm.ad(bm.java:424)
	at bm.ui(bm.java)
	at bm.run(bm.java:57672)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</p>
</details> 

I don't fully understand how the [conditional on line 216 passed](https://github.com/Toofifty/easy-giantsfoundry/blob/master/src/main/java/com/toofifty/easygiantsfoundry/FoundryOverlay3D.java#L216C9-L216C62) just before the NPE. But maybe consider adding some more logic? Could also be some weird bug with runelite.

Some more potentially relevant info:

- Runelite 1.10.17.2
- Oldschool Rev 218
- Launcher Version 2.6.8

**Comment by Toofifty** [comment]
Hey @ZacBlanco, thanks for submitting an issue :)

I don't think exceptions thrown inside overlays can break anything (see [the `safeRender` implementation here](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java#L710)), although this does look like it's something we can fix. I think the widget may have been in memory while a reference to the Kovac NPC was not, passing the check on L216 but causing an exception trying to access Kovac on L218.

When this happened, what type of overlays crashed? Overlay panels, world (npc/object) overlays, or both? There's been a few times that I've had plugins throwing exceptions on render but it never prevented other overlays from showing.

**Comment by ZacBlanco** [comment]
It's very possible there was something else happening in runelite that crashed the overlays. I can't recall if panel overlays crashed but I know for sure that object/NPC overlays crashed entirely (e.g. fishing spot overlay with the images+outlines) ceased appearing at the same time the plugin crashed. The stacktrace posted was the only info that the runelite console spit out at that time. There didn't seem to be any messages afterwards.

**Comment by pwatts6060** [comment]
This issue hasn't come up again and experienced similar things when you disconnect where fishing spots overlay disappear.
